# Copyright 2014 Cisco Systems, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#
# @author: Juergen Brendel, Cisco Systems, Inc.

# -----------------------------------------------------------------------------
# Playbook to setup basic system configuration, such as users, basic
# system packages and use of APT and PIP caches (if so specified).
# -----------------------------------------------------------------------------

---

#
# Ensure user and group exist. The 'ubuntu' user comes with the
# operating system...
#
- name: Ensure presence of {{ USERS.stack_user }} user...
  user: >
      name={{ USERS.stack_user }}
      state=present
      shell=/bin/bash
      groups="sudo"

#
# Installation of necessary software packages
#
- name: Install necessary packages
  apt: pkg={{ item }} state=present
  with_items:
      - openvswitch-switch
      - git-core
      - python-argparse
      - cloud-init
      - python-psutil
      - python-pip
      - python-dev

